# Add documentation label to any change in documentation related files
documentation:
  - label: 'documentation'
    paths:
      - 'docs/*'
      - 'docs/**/*'
      - 'README.md'
      - '**/README.md'
      - 'CONTRIBUTING.md'

maintenance:
  - label: 'maintenance'
    paths:
      - '.vscode/*'
      - '.vscode/**/*'
      - '.github/*'
      - '.github/**/*'
      - '.reuse/*'
      - 'LICENSES/*'
      - '.editorconfig'
      - '.gitignore'
      - '**/.gitignore'
      - 'build.py'
      - '**/build.py'
